apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  
  #the pod template
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      containers:
        - name:  ns-redis
          ports:
            - containerPort: 6379
          image: redis:alpine

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis